### ISSUE TITLE
Help running 

### ISSUE THREAD

**Issue by oxhey** [ordazl/Meteor-Presentation#1]
Im trying to run this on debian and keep getting this error when doing meteor from the termial when im in either the public or server folder:

While building the application : 
error : no such package : "iron-router"
error : no such package : "reveal-js"
error : no such package : "collectionFS"
error : no such package : "cfs-filesystem"

**Comment by ordazl** [comment]
This project was created before the meteor team implemented the new packaging system (v0.9 iirc), so the packages are not properly namespace and can't be downloaded. You'll need to remove each package individually (meteor remove iron-route, ect.) and run meteor update to get the latest version. Then after that re-add each package (I recommend https://atmospherejs.com/ to search for them). With that in mind even after updating I don't know if it will run. Since this project hasn't been touched in ~8 Months it probably would be best to start from scratch...

**Comment by oxhey** [comment]
could you put up a running demo , so i can see if its worth trying ot get this to work?

**Comment by ordazl** [comment]
I just pushed an update that should it allow on meteor 1.0.0. You should be able to pull the changes and run the application

**Comment by oxhey** [comment]
Thanks .

**Comment by oxhey** [comment]
It doesnt work . cannot read inpit from _id - modal.js ?

**Comment by ordazl** [comment]
You will need to create a user before creating a presentation. After that everything else was/is pretty much a work in progress (far from feature complete and production ready) so bugs are very much expected.
